<%@ page language='java' contentType='text/html; charset=UTF-8'
	pageEncoding='UTF-8'%>
<%@ taglib uri='http://java.sun.com/jsp/jstl/core' prefix='c'%>

<!DOCTYPE html>
<html>
<head>
<meta charset='UTF-8'>
<title>RotomDex</title>
<jsp:include page='bootstrapHead.jsp'></jsp:include>
</head>
<body>
	<main class='contaiiner-fluid'>

		<section class='header' id='header'>
			<a href="/"><img src='images/Rotom_Pokedex_small.png'
				class='logo' id='logo' /></a>
			<h1 class="header">Welcome to RotomDex!</h1>
		</section>

		<section class="forms">
			<h3>Create a New Pokemon!</h3>
			<form action="createPokemon.do" method="POST">
				<label for="name" class="formLabels">Name:</label>
				<input type="text" name="name" id="name"><br>
				<label for="type1" class="formLabels">Type 1:</label>
				<select name="type1" id="type1">
					<option value="Normal">Normal</option>
					<option value="Fire">Fire</option>
					<option value="Water">Water</option>
					<option value="Grass">Grass</option>
					<option value="Electric">Electric</option>
					<option value="Ice">Ice</option>
					<option value="Fighting">Fighting</option>
					<option value="Poison">Poison</option>
					<option value="Ground">Ground</option>
					<option value="Flying">Flying</option>
					<option value="Psychic">Psychic</option>
					<option value="Bug">Bug</option>
					<option value="Rock">Rock</option>
					<option value="Ghost">Ghost</option>
					<option value="Dark">Dark</option>
					<option value="Dragon">Dragon</option>
					<option value="Steel">Steel</option>
					<option value="Fairy">Fairy</option>
				</select><br>
				<label for="type1" class="formLabels">Type 2:</label>
				<select name="type2" id="type2">
					<option value="Normal">Normal</option>
					<option value="Fire">Fire</option>
					<option value="Water">Water</option>
					<option value="Grass">Grass</option>
					<option value="Electric">Electric</option>
					<option value="Ice">Ice</option>
					<option value="Fighting">Fighting</option>
					<option value="Poison">Poison</option>
					<option value="Ground">Ground</option>
					<option value="Flying">Flying</option>
					<option value="Psychic">Psychic</option>
					<option value="Bug">Bug</option>
					<option value="Rock">Rock</option>
					<option value="Ghost">Ghost</option>
					<option value="Dark">Dark</option>
					<option value="Dragon">Dragon</option>
					<option value="Steel">Steel</option>
					<option value="Fairy">Fairy</option>
				</select><br>
				<label for="ability1" class="formLabels">Ability 1:</label>
				<input type="text" name="ability1" id="ability1"><br>
				<label for="ability2" class="formLabels">Ability 2:</label>
				<input type="text" name="ability2" id="ability2"><br>
				<label for="specAbility" class="formLabels">Special Ability:</label>
				<input type="text" name="specAbility" id="specAbility"><br>
				<label for="specAttack" class="formLabels">Special Attack:</label>
				<input type="text" name="specAttack" id="specAttack"><br>
				<label for="specDefense" class="formLabels">Special Defense:</label>
				<input type="text" name="specDefense" id="specDefense"><br>
				<label for="hp" class="formLabels">Hit Points (10-100):</label>
				<input type="number" name="hp" id="hp" min="10" max="100"><br>
				<label for="attack" class="formLabels">Attack (10-100):</label>
				<input type="number" name="attack" id="attack" min="10" max="100"><br>
				<label for="defense" class="formLabels">Defense (10-100):</label>
				<input type="number" name="defense" id="defense" min="10" max="100"><br>
				<label for="speed" class="formLabels">Speed (10-100):</label>
				<input type="number" name="speed" id="speed" min="10" max="100"><br>
				<label for="weight" class="formLabels">Weight (lbs):</label>
				<input type="number" name="weight" id="weight" min="10" max="350" step="0.01"><br>
				<label for="height" class="formLabels">Height (inches):</label>
				<input type="number" name="height" id="height" min="10" max="100"><br>
				<label for="classtype" class="formLabels">Pokemon Class:</label>
				<select name="classtype" id="classtype">
					<option value="Acorn Pokemon">Acorn Pokemon</option>
					<option value="Affection Pokemon">Affection Pokemon</option>
					<option value="Agent Pokemon">Agent Pokemon</option>
					<option value="Aggressive Pokemon">Aggressive Pokemon</option>
					<option value="Allotriophage Pokemon">Allotriophage Pokemon</option>
					<option value="Alloy Pokemon">Alloy Pokemon</option>
					<option value="Amplification Pokemon">Amplification Pokemon</option>
					<option value="Ancient Shrimp Pokemon">Ancient Shrimp Pokemon</option>
					<option value="Ancient Turtle Pokemon">Ancient Turtle Pokemon</option>
					<option value="Anglerfish Pokemon">Anglerfish Pokemon</option>
					<option value="Anteater Pokemon">Anteater Pokemon</option>
					<option value="Antenna Pokemon">Antenna Pokemon</option>
					<option value="Antlion Larva Pokemon">Antlion Larva Pokemon</option>
					<option value="Apple Juice Pokemon">Apple Juice Pokemon</option>
					<option value="Apple Living Pokemon">Apple Living Pokemon</option>
					<option value="Apple Wing Pokemon">Apple Wing Pokemon</option>
					<option value="Approaching Death Pokemon">Approaching Death Pokemon</option>
					<option value="Armor Bird Pokemon">Armor Bird Pokemon</option>
					<option value="Armor Pokemon">Armor Pokemon</option>
					<option value="Armored Pokemon">Armored Pokemon</option>
					<option value="Arrow Feather Pokemon">Arrow Feather Pokemon</option>
					<option value="Artificial Pokemon">Artificial Pokemon</option>
					<option value="Association Pokemon">Association Pokemon</option>
					<option value="Atrocious Pokemon">Atrocious Pokemon</option>
					<option value="Aurora Pokemon">Aurora Pokemon</option>
					<option value="Baby Pokemon">Baby Pokemon</option>
					<option value="Bad Monkey Pokemon">Bad Monkey Pokemon</option>
					<option value="Bagworm Moth Pokemon">Bagworm Moth Pokemon</option>
					<option value="Bagworm Pokemon">Bagworm Pokemon</option>
					<option value="Bakeneko Pokemon">Bakeneko Pokemon</option>
					<option value="Ball Pokemon">Ball Pokemon</option>
					<option value="Ball Roll Pokemon">Ball Roll Pokemon</option>
					<option value="Ball Whale Pokemon">Ball Whale Pokemon</option>
					<option value="Balloon Pokemon">Balloon Pokemon</option>
					<option value="Barrier Pokemon">Barrier Pokemon</option>
					<option value="Bat Pokemon">Bat Pokemon</option>
					<option value="Battery Pokemon">Battery Pokemon</option>
					<option value="Battle Formation Pokemon">Battle Formation Pokemon</option>
					<option value="Beak Pokemon">Beak Pokemon</option>
					<option value="Beat Pokemon">Beat Pokemon</option>
					<option value="Beauty Pokemon">Beauty Pokemon</option>
					<option value="Beaver Pokemon">Beaver Pokemon</option>
					<option value="Beckoning Pokemon">Beckoning Pokemon</option>
					<option value="Bee Fly Pokemon">Bee Fly Pokemon</option>
					<option value="Bee Larva Pokemon">Bee Larva Pokemon</option>
					<option value="Beehive Pokemon">Beehive Pokemon</option>
					<option value="Beguiling Pokemon">Beguiling Pokemon</option>
					<option value="Bell Pokemon">Bell Pokemon</option>
					<option value="Big Boss Pokemon">Big Boss Pokemon</option>
					<option value="Big Fire Pig Pokemon">Big Fire Pig Pokemon</option>
					<option value="Big Fish Pokemon">Big Fish Pokemon</option>
					<option value="Big Horn Pokemon">Big Horn Pokemon</option>
					<option value="Big Jaw Pokemon">Big Jaw Pokemon</option>
					<option value="Bird of Prey Pokemon">Bird of Prey Pokemon</option>
					<option value="Bird Pokemon">Bird Pokemon</option>
					<option value="Bite Down Pokemon">Bite Down Pokemon</option>
					<option value="Bite Pokemon">Bite Pokemon</option>
					<option value="Bivalve Pokemon">Bivalve Pokemon</option>
					<option value="Black Tea Pokemon">Black Tea Pokemon</option>
					<option value="Black Yin Pokemon">Black Yin Pokemon</option>
					<option value="Black-Tailed Gull Pokemon">Black-Tailed Gull Pokemon</option>
					<option value="Blade Feather Pokemon">Blade Feather Pokemon</option>
					<option value="Blade Pokemon">Blade Pokemon</option>
					<option value="Blazing Pokemon">Blazing Pokemon</option>
					<option value="Blessing Pokemon">Blessing Pokemon</option>
					<option value="Blimp Pokemon">Blimp Pokemon</option>
					<option value="Blizzard Pokemon">Blizzard Pokemon</option>
					<option value="Blocking Pokemon">Blocking Pokemon</option>
					<option value="Bone Eagle Pokemon">Bone Eagle Pokemon</option>
					<option value="Bone Lover Pokemon">Bone Lover Pokemon</option>
					<option value="Bonsai Pokemon">Bonsai Pokemon</option>
					<option value="Boundary Pokemon">Boundary Pokemon</option>
					<option value="Bouquet Pokemon">Bouquet Pokemon</option>
					<option value="Boxing Pokemon">Boxing Pokemon</option>
					<option value="Brain Pokemon">Brain Pokemon</option>
					<option value="Broadaxe Pokemon">Broadaxe Pokemon</option>
					<option value="Bronze Bell Pokemon">Bronze Bell Pokemon</option>
					<option value="Bronze Pokemon">Bronze Pokemon</option>
					<option value="Bronze Statue Pokemon">Bronze Statue Pokemon</option>
					<option value="Brutal Pokemon">Brutal Pokemon</option>
					<option value="Brute Pokemon">Brute Pokemon</option>
					<option value="Bruxism Pokemon">Bruxism Pokemon</option>
					<option value="Bud Pokemon">Bud Pokemon</option>
					<option value="Bug Catcher Pokemon">Bug Catcher Pokemon</option>
					<option value="Bugle Beak Pokemon">Bugle Beak Pokemon</option>
					<option value="Buildup Pokemon">Buildup Pokemon</option>
					<option value="Bullet Pokemon">Bullet Pokemon</option>
					<option value="Burrowing Pokemon">Burrowing Pokemon</option>
					<option value="Bustling Pokemon">Bustling Pokemon</option>
					<option value="Butterfly Pokemon">Butterfly Pokemon</option>
					<option value="Cactus Pokemon">Cactus Pokemon</option>
					<option value="Calamity Pokemon">Calamity Pokemon</option>
					<option value="Caldera Pokemon">Caldera Pokemon</option>
					<option value="Calm Pokemon">Calm Pokemon</option>
					<option value="Candle Pokemon">Candle Pokemon</option>
					<option value="Cannon Pokemon">Cannon Pokemon</option>
					<option value="Caretaker Pokemon">Caretaker Pokemon</option>
					<option value="Caterpillar Pokemon">Caterpillar Pokemon</option>
					<option value="Cavalry Pokemon">Cavalry Pokemon</option>
					<option value="Cave Pokemon">Cave Pokemon</option>
					<option value="Cavern Pokemon">Cavern Pokemon</option>
					<option value="Cell Pokemon">Cell Pokemon</option>
					<option value="Centipede Pokemon">Centipede Pokemon</option>
					<option value="Cheerful Pokemon">Cheerful Pokemon</option>
					<option value="Cheering Pokemon">Cheering Pokemon</option>
					<option value="Cherry Blossom Pokemon">Cherry Blossom Pokemon</option>
					<option value="Cherry Pokemon">Cherry Pokemon</option>
					<option value="Chick Pokemon">Chick Pokemon</option>
					<option value="Chicken Pokemon">Chicken Pokemon</option>
					<option value="Child-Raising Pokemon">Child-Raising Pokemon</option>
					<option value="Chinchilla Pokemon">Chinchilla Pokemon</option>
					<option value="Chrysalis Pokemon">Chrysalis Pokemon</option>
					<option value="Circle Ball Pokemon">Circle Ball Pokemon</option>
					<option value="Clap Pokemon">Clap Pokemon</option>
					<option value="Claw Pokemon">Claw Pokemon</option>
					<option value="Clay Figure Pokemon">Clay Figure Pokemon</option>
					<option value="Climbing Pokemon">Climbing Pokemon</option>
					<option value="Clinging Pokemon">Clinging Pokemon</option>
					<option value="Coal Pokemon">Coal Pokemon</option>
					<option value="Cobra Pokemon">Cobra Pokemon</option>
					<option value="Coconut Pokemon">Coconut Pokemon</option>
					<option value="Cocoon Centipede Pokemon">Cocoon Centipede Pokemon</option>
					<option value="Coffin Pokemon">Coffin Pokemon</option>
					<option value="Color Change Pokemon">Color Change Pokemon</option>
					<option value="Comedian Pokemon">Comedian Pokemon</option>
					<option value="Compass Pokemon">Compass Pokemon</option>
					<option value="Continent Pokemon">Continent Pokemon</option>
					<option value="Cooperation Pokemon">Cooperation Pokemon</option>
					<option value="Coral Pokemon">Coral Pokemon</option>
					<option value="Cotton Ball Pokemon">Cotton Ball Pokemon</option>
					<option value="Cotton Bird Pokemon">Cotton Bird Pokemon</option>
					<option value="Cotton Candy Pokemon">Cotton Candy Pokemon</option>
					<option value="Cotton Decoration Pokemon">Cotton Decoration Pokemon</option>
					<option value="Cottonweed Pokemon">Cottonweed Pokemon</option>
					<option value="Courier Pokemon">Courier Pokemon</option>
					<option value="Courting Pokemon">Courting Pokemon</option>
					<option value="Cream Pokemon">Cream Pokemon</option>
					<option value="Creation Pokemon">Creation Pokemon</option>
					<option value="Crescent Moon Pokemon">Crescent Moon Pokemon</option>
					<option value="Cricket Pokemon">Cricket Pokemon</option>
					<option value="Cruel Pokemon">Cruel Pokemon</option>
					<option value="Crystal Pokemon">Crystal Pokemon</option>
					<option value="Curse Fox Pokemon">Curse Fox Pokemon</option>
					<option value="Dairy Cow Pokemon">Dairy Cow Pokemon</option>
					<option value="Dance Pokemon">Dance Pokemon</option>
					<option value="Daring Pokemon">Daring Pokemon</option>
					<option value="Dark Pokemon">Dark Pokemon</option>
					<option value="Darkness Pokemon">Darkness Pokemon</option>
					<option value="Daruma Pokemon">Daruma Pokemon</option>
					<option value="Deceiver Pokemon">Deceiver Pokemon</option>
					<option value="Deep Earth Pokemon">Deep Earth Pokemon</option>
					<option value="Deep Sea Pokemon">Deep Sea Pokemon</option>
					<option value="Desert Crocodile Pokemon">Desert Crocodile Pokemon</option>
					<option value="Deshelled Pokemon">Deshelled Pokemon</option>
					<option value="Destruction Pokemon">Destruction Pokemon</option>
					<option value="Diaper Pokemon">Diaper Pokemon</option>
					<option value="Dignified Pokemon">Dignified Pokemon</option>
					<option value="Discharge Pokemon">Discharge Pokemon</option>
					<option value="Disguise Pokemon">Disguise Pokemon</option>
					<option value="Diving Pokemon">Diving Pokemon</option>
					<option value="DNA Pokemon">DNA Pokemon</option>
					<option value="Dog Pokemon">Dog Pokemon</option>
					<option value="Doll Pokemon">Doll Pokemon</option>
					<option value="Donkey Pokemon">Donkey Pokemon</option>
					<option value="Dozing Pokemon">Dozing Pokemon</option>
					<option value="Draft Horse Pokemon">Draft Horse Pokemon</option>
					<option value="Dragon Ball Pokemon">Dragon Ball Pokemon</option>
					<option value="Dragon Pokemon">Dragon Pokemon</option>
					<option value="Drawn Sword Pokemon">Drawn Sword Pokemon</option>
					<option value="Dream Eater Pokemon">Dream Eater Pokemon</option>
					<option value="Drill Pokemon">Drill Pokemon</option>
					<option value="Drummer Pokemon">Drummer Pokemon</option>
					<option value="Duck Pokemon">Duck Pokemon</option>
					<option value="Duckling Pokemon">Duckling Pokemon</option>
					<option value="Eaglet Pokemon">Eaglet Pokemon</option>
					<option value="Egg Pokemon">Egg Pokemon</option>
					<option value="Electric Fish Pokemon">Electric Fish Pokemon</option>
					<option value="Electric Pokemon">Electric Pokemon</option>
					<option value="Electric Shock Pokemon">Electric Shock Pokemon</option>
					<option value="Electric Spider Pokemon">Electric Spider Pokemon</option>
					<option value="Electric Squirrel Pokemon">Electric Squirrel Pokemon</option>
					<option value="Electrified Pokemon">Electrified Pokemon</option>
					<option value="Electron Pokemon">Electron Pokemon</option>
					<option value="Embrace Pokemon">Embrace Pokemon</option>
					<option value="Emotion Pokemon">Emotion Pokemon</option>
					<option value="Emperor Pokemon">Emperor Pokemon</option>
					<option value="Endurance Pokemon">Endurance Pokemon</option>
					<option value="Eruption Pokemon">Eruption Pokemon</option>
					<option value="Evil Fox Pokemon">Evil Fox Pokemon</option>
					<option value="Evil Pokemon">Evil Pokemon</option>
					<option value="Evolution Pokemon">Evolution Pokemon</option>
					<option value="Explosion Fume Pokemon">Explosion Fume Pokemon</option>
					<option value="Explosion Turtle Pokemon">Explosion Turtle Pokemon</option>
					<option value="Eyeball Pokemon">Eyeball Pokemon</option>
					<option value="Face Pokemon">Face Pokemon</option>
					<option value="Fairy Pokemon">Fairy Pokemon</option>
					<option value="Faithful Dog Pokemon">Faithful Dog Pokemon</option>
					<option value="Fang Scorpion Pokemon">Fang Scorpion Pokemon</option>
					<option value="Fang Snake Pokemon">Fang Snake Pokemon</option>
					<option value="Feeling Pokemon">Feeling Pokemon</option>
					<option value="Fermentation Pokemon">Fermentation Pokemon</option>
					<option value="Ferocious Pokemon">Ferocious Pokemon</option>
					<option value="Fertility Pokemon">Fertility Pokemon</option>
					<option value="Fire Cat Pokemon">Fire Cat Pokemon</option>
					<option value="Fire Horse Pokemon">Fire Horse Pokemon</option>
					<option value="Fire Mouse Pokemon">Fire Mouse Pokemon</option>
					<option value="Fire Pig Pokemon">Fire Pig Pokemon</option>
					<option value="Firefly Pokemon">Firefly Pokemon</option>
					<option value="Fireworks Pokemon">Fireworks Pokemon</option>
					<option value="Fish Pokemon">Fish Pokemon</option>
					<option value="Five Star Pokemon">Five Star Pokemon</option>
					<option value="Flailing Pokemon">Flailing Pokemon</option>
					<option value="Flame Crocodile Pokemon">Flame Crocodile Pokemon</option>
					<option value="Flame Pokemon">Flame Pokemon</option>
					<option value="Flash Pokemon">Flash Pokemon</option>
					<option value="Float Whale Pokemon">Float Whale Pokemon</option>
					<option value="Floating Pokemon">Floating Pokemon</option>
					<option value="Floating Weed Pokemon">Floating Weed Pokemon</option>
					<option value="Flower Decoration Pokemon">Flower Decoration Pokemon</option>
					<option value="Flower Picker Pokemon">Flower Picker Pokemon</option>
					<option value="Flower Pokemon">Flower Pokemon</option>
					<option value="Flower Sickle Pokemon">Flower Sickle Pokemon</option>
					<option value="Fluff Pokemon">Fluff Pokemon</option>
					<option value="Flycatcher Pokemon">Flycatcher Pokemon</option>
					<option value="Flying Scorpion Pokemon">Flying Scorpion Pokemon</option>
					<option value="Flying Squirrel Pokemon">Flying Squirrel Pokemon</option>
					<option value="Foam Frog Pokemon">Foam Frog Pokemon</option>
					<option value="Foam-Spitting Pokemon">Foam-Spitting Pokemon</option>
					<option value="Forest Cloak Pokemon">Forest Cloak Pokemon</option>
					<option value="Forest Lizard Pokemon">Forest Lizard Pokemon</option>
					<option value="Fossil Pokemon">Fossil Pokemon</option>
					<option value="Fox Pokemon">Fox Pokemon</option>
					<option value="Fragrance Pokemon">Fragrance Pokemon</option>
					<option value="Freezing Pokemon">Freezing Pokemon</option>
					<option value="Fresh Snow Pokemon">Fresh Snow Pokemon</option>
					<option value="Fresh Verdure Pokemon">Fresh Verdure Pokemon</option>
					<option value="Freshwater Crab Pokemon">Freshwater Crab Pokemon</option>
					<option value="Frog Pokemon">Frog Pokemon</option>
					<option value="Frost-Covered Tree Pokemon">Frost-Covered Tree Pokemon</option>
					<option value="Frozen Pokemon">Frozen Pokemon</option>
					<option value="Fruit Pokemon">Fruit Pokemon</option>
					<option value="Garbage Bag Pokemon">Garbage Bag Pokemon</option>
					<option value="Garbage Dump Pokemon">Garbage Dump Pokemon</option>
					<option value="Garden Pokemon">Garden Pokemon</option>
					<option value="Gaseous Pokemon">Gaseous Pokemon</option>
					<option value="Gathering Pokemon">Gathering Pokemon</option>
					<option value="Gear Pokemon">Gear Pokemon</option>
					<option value="Generator Pokemon">Generator Pokemon</option>
					<option value="Genetic Pokemon">Genetic Pokemon</option>
					<option value="Gentle Pokemon">Gentle Pokemon</option>
					<option value="Ghost Flame Pokemon">Ghost Flame Pokemon</option>
					<option value="Gigantic Pokemon">Gigantic Pokemon</option>
					<option value="Glinting Eyes Pokemon">Glinting Eyes Pokemon</option>
					<option value="Glowing Pokemon">Glowing Pokemon</option>
					<option value="Gluttonous Pokemon">Gluttonous Pokemon</option>
					<option value="Goldfish Pokemon">Goldfish Pokemon</option>
					<option value="Golem Pokemon">Golem Pokemon</option>
					<option value="Good Walker Pokemon">Good Walker Pokemon</option>
					<option value="Grasping Pokemon">Grasping Pokemon</option>
					<option value="Grass Cat Pokemon">Grass Cat Pokemon</option>
					<option value="Grass Feather Pokemon">Grass Feather Pokemon</option>
					<option value="Grass Monkey Pokemon">Grass Monkey Pokemon</option>
					<option value="Grass Snake Pokemon">Grass Snake Pokemon</option>
					<option value="Grassland Pokemon">Grassland Pokemon</option>
					<option value="Gratitude Pokemon">Gratitude Pokemon</option>
					<option value="Greedy Pokemon">Greedy Pokemon</option>
					<option value="Grove Pokemon">Grove Pokemon</option>
					<option value="Grudge Fox Pokemon">Grudge Fox Pokemon</option>
					<option value="Grudge Pokemon">Grudge Pokemon</option>
					<option value="Gulp Pokemon">Gulp Pokemon</option>
					<option value="Guts Pokemon">Guts Pokemon</option>
					<option value="Hairy Caterpillar Pokemon">Hairy Caterpillar Pokemon</option>
					<option value="Happiness Pokemon">Happiness Pokemon</option>
					<option value="Hard-Headed Pokemon">Hard-Headed Pokemon</option>
					<option value="Head Butt Pokemon">Head Butt Pokemon</option>
					<option value="Headbutt Bull Pokemon">Headbutt Bull Pokemon</option>
					<option value="Headstand Pokemon">Headstand Pokemon</option>
					<option value="Hearing Pokemon">Hearing Pokemon</option>
					<option value="Heat Generation Pokemon">Heat Generation Pokemon</option>
					<option value="Heavenly Body Pokemon">Heavenly Body Pokemon</option>
					<option value="Heavyweight Pokemon">Heavyweight Pokemon</option>
					<option value="Heel Pokemon">Heel Pokemon</option>
					<option value="Herb Pokemon">Herb Pokemon</option>
					<option value="Hermit Crab Pokemon">Hermit Crab Pokemon</option>
					<option value="Hibernation Pokemon">Hibernation Pokemon</option>
					<option value="High Pressure Pokemon">High Pressure Pokemon</option>
					<option value="High Temperature Pokemon">High Temperature Pokemon</option>
					<option value="High Water Pokemon">High Water Pokemon</option>
					<option value="Hippo Pokemon">Hippo Pokemon</option>
					<option value="Hopping Pokemon">Hopping Pokemon</option>
					<option value="Horsehair Crab Pokemon">Horsehair Crab Pokemon</option>
					<option value="Humanoid Pokemon">Humanoid Pokemon</option>
					<option value="Humming Pokemon">Humming Pokemon</option>
					<option value="Husk Pokemon">Husk Pokemon</option>
					<option value="Hypnosis Pokemon">Hypnosis Pokemon</option>
					<option value="Ice and Snow Pokemon">Ice and Snow Pokemon</option>
					<option value="Ice Breaker Pokemon">Ice Breaker Pokemon</option>
					<option value="Ice Floe Pokemon">Ice Floe Pokemon</option>
					<option value="Ice Moth Pokemon">Ice Moth Pokemon</option>
					<option value="Iceberg Pokemon">Iceberg Pokemon</option>
					<option value="Idol Pokemon">Idol Pokemon</option>
					<option value="Ill-Natured Pokemon">Ill-Natured Pokemon</option>
					<option value="Illusory Fox Pokemon">Illusory Fox Pokemon</option>
					<option value="Imitation Pokemon">Imitation Pokemon</option>
					<option value="Infinity Pokemon">Infinity Pokemon</option>
					<option value="Insect Pokemon">Insect Pokemon</option>
					<option value="Iron Ant Pokemon">Iron Ant Pokemon</option>
					<option value="Iron Armor Pokemon">Iron Armor Pokemon</option>
					<option value="Iron Ball Pokemon">Iron Ball Pokemon</option>
					<option value="Iron Claw Pokemon">Iron Claw Pokemon</option>
					<option value="Iron Leg Pokemon">Iron Leg Pokemon</option>
					<option value="Iron Pokemon">Iron Pokemon</option>
					<option value="Iron Snake Pokemon">Iron Snake Pokemon</option>
					<option value="Iron Will Pokemon">Iron Will Pokemon</option>
					<option value="Japanese Robin Pokemon">Japanese Robin Pokemon</option>
					<option value="Jaw Ax Pokemon">Jaw Ax Pokemon</option>
					<option value="Jellyfish Pokemon">Jellyfish Pokemon</option>
					<option value="Jet Pokemon">Jet Pokemon</option>
					<option value="Jewel Pokemon">Jewel Pokemon</option>
					<option value="Judo Pokemon">Judo Pokemon</option>
					<option value="Jujutsu Pokemon">Jujutsu Pokemon</option>
					<option value="Jungle Pokemon">Jungle Pokemon</option>
					<option value="Karate Pokemon">Karate Pokemon</option>
					<option value="Kenpo Pokemon">Kenpo Pokemon</option>
					<option value="Kenzan Pokemon">Kenzan Pokemon</option>
					<option value="Key Ring Pokemon">Key Ring Pokemon</option>
					<option value="Kick Pokemon">Kick Pokemon</option>
					<option value="King Pokemon">King Pokemon</option>
					<option value="Kiss Pokemon">Kiss Pokemon</option>
					<option value="Kite Pokemon">Kite Pokemon</option>
					<option value="Kitten Pokemon">Kitten Pokemon</option>
					<option value="Knowledge Pokemon">Knowledge Pokemon</option>
					<option value="Lamp Pokemon">Lamp Pokemon</option>
					<option value="Land Shark Pokemon">Land Shark Pokemon</option>
					<option value="Land Snake Pokemon">Land Snake Pokemon</option>
					<option value="Land Spirit Pokemon">Land Spirit Pokemon</option>
					<option value="Large Voice Pokemon">Large Voice Pokemon</option>
					<option value="Larva Pokemon">Larva Pokemon</option>
					<option value="Launch Pokemon">Launch Pokemon</option>
					<option value="Launcher Pokemon">Launcher Pokemon</option>
					<option value="Lava Pokemon">Lava Pokemon</option>
					<option value="Lazy Pokemon">Lazy Pokemon</option>
					<option value="Leaf Pokemon">Leaf Pokemon</option>
					<option value="Legend Pokemon">Legend Pokemon</option>
					<option value="Licking Pokemon">Licking Pokemon</option>
					<option value="Life Pokemon">Life Pokemon</option>
					<option value="Light Pokemon">Light Pokemon</option>
					<option value="Lightning Pokemon">Lightning Pokemon</option>
					<option value="Lightning Strike Pokemon">Lightning Strike Pokemon</option>
					<option value="Live Coal Pokemon">Live Coal Pokemon</option>
					<option value="Lizard Pokemon">Lizard Pokemon</option>
					<option value="Lonely Pokemon">Lonely Pokemon</option>
					<option value="Long Leg Pokemon">Long Leg Pokemon</option>
					<option value="Long Neck Pokemon">Long Neck Pokemon</option>
					<option value="Long Nose Pokemon">Long Nose Pokemon</option>
					<option value="Long Tail Pokemon">Long Tail Pokemon</option>
					<option value="Long Torso Pokemon">Long Torso Pokemon</option>
					<option value="Longevity Pokemon">Longevity Pokemon</option>
					<option value="Lookout Pokemon">Lookout Pokemon</option>
					<option value="Love-Hate Pokemon">Love-Hate Pokemon</option>
					<option value="Lowest-Class Pokemon">Lowest-Class Pokemon</option>
					<option value="Luminescence Pokemon">Luminescence Pokemon</option>
					<option value="Mach Pokemon">Mach Pokemon</option>
					<option value="Magical Pokemon">Magical Pokemon</option>
					<option value="Magnet Pokemon">Magnet Pokemon</option>
					<option value="Magnetic Field Pokemon">Magnetic Field Pokemon</option>
					<option value="Majin Pokemon">Majin Pokemon</option>
					<option value="Malicious Pokemon">Malicious Pokemon</option>
					<option value="Man-made Pokemon">Man-made Pokemon</option>
					<option value="Manipulation Pokemon">Manipulation Pokemon</option>
					<option value="Mantis Pokemon">Mantis Pokemon</option>
					<option value="Mantle Pokemon">Mantle Pokemon</option>
					<option value="Martial Arts Pokemon">Martial Arts Pokemon</option>
					<option value="Meditation Pokemon">Meditation Pokemon</option>
					<option value="Mega Centipede Pokemon">Mega Centipede Pokemon</option>
					<option value="Megalith Pokemon">Megalith Pokemon</option>
					<option value="Megaton Pokemon">Megaton Pokemon</option>
					<option value="Melody Pokemon">Melody Pokemon</option>
					<option value="Menacing Pokemon">Menacing Pokemon</option>
					<option value="Merry Pokemon">Merry Pokemon</option>
					<option value="Meteor Pokemon">Meteor Pokemon</option>
					<option value="Meteorite Pokemon">Meteorite Pokemon</option>
					<option value="Migration Pokemon">Migration Pokemon</option>
					<option value="Mime Pokemon">Mime Pokemon</option>
					<option value="Mischief Pokemon">Mischief Pokemon</option>
					<option value="Mischievous Pokemon">Mischievous Pokemon</option>
					<option value="Mitosis Pokemon">Mitosis Pokemon</option>
					<option value="Mole Pokemon">Mole Pokemon</option>
					<option value="Monarch Pokemon">Monarch Pokemon</option>
					<option value="Mongoose Pokemon">Mongoose Pokemon</option>
					<option value="Monster Scorpion Pokemon">Monster Scorpion Pokemon</option>
					<option value="Moon Pokemon">Moon Pokemon</option>
					<option value="Moonlight Pokemon">Moonlight Pokemon</option>
					<option value="Mouse Pokemon">Mouse Pokemon</option>
					<option value="Muscle Pokemon">Muscle Pokemon</option>
					<option value="Mushroom Pokemon">Mushroom Pokemon</option>
					<option value="Music Note Pokemon">Music Note Pokemon</option>
					<option value="Mysterious Pokemon">Mysterious Pokemon</option>
					<option value="Naughty Pokemon">Naughty Pokemon</option>
					<option value="Nebula Pokemon">Nebula Pokemon</option>
					<option value="Neon Pokemon">Neon Pokemon</option>
					<option value="New Leaf Pokemon">New Leaf Pokemon</option>
					<option value="New Species Pokemon">New Species Pokemon</option>
					<option value="Night Cry Pokemon">Night Cry Pokemon</option>
					<option value="Ninja Pokemon">Ninja Pokemon</option>
					<option value="Noise Pokemon">Noise Pokemon</option>
					<option value="Nursing Pokemon">Nursing Pokemon</option>
					<option value="Nut Pokemon">Nut Pokemon</option>
					<option value="Ocean Pokemon">Ocean Pokemon</option>
					<option value="Ogre Dragonfly Pokemon">Ogre Dragonfly Pokemon</option>
					<option value="Old Tree Pokemon">Old Tree Pokemon</option>
					<option value="Oldest Bird Pokemon">Oldest Bird Pokemon</option>
					<option value="One Horn Pokemon">One Horn Pokemon</option>
					<option value="Optimistic Pokemon">Optimistic Pokemon</option>
					<option value="Order Pokemon">Order Pokemon</option>
					<option value="Ore Pokemon">Ore Pokemon</option>
					<option value="Owl Pokemon">Owl Pokemon</option>
					<option value="Painter Pokemon">Painter Pokemon</option>
					<option value="Paleozoic Pokemon">Paleozoic Pokemon</option>
					<option value="Palm Thrust Pokemon">Palm Thrust Pokemon</option>
					<option value="Parasite Pokemon">Parasite Pokemon</option>
					<option value="Parent and Child Pokemon">Parent and Child Pokemon</option>
					<option value="Patient Pokemon">Patient Pokemon</option>
					<option value="Peat Pokemon">Peat Pokemon</option>
					<option value="Penguin Pokemon">Penguin Pokemon</option>
					<option value="Perfume Pokemon">Perfume Pokemon</option>
					<option value="Pig Boar Pokemon">Pig Boar Pokemon</option>
					<option value="Pig Monkey Pokemon">Pig Monkey Pokemon</option>
					<option value="Pincer Pokemon">Pincer Pokemon</option>
					<option value="Plasma Pokemon">Plasma Pokemon</option>
					<option value="Playing House Pokemon">Playing House Pokemon</option>
					<option value="Poison Bag Pokemon">Poison Bag Pokemon</option>
					<option value="Poison Bee Pokemon">Poison Bee Pokemon</option>
					<option value="Poison Gas Pokemon">Poison Gas Pokemon</option>
					<option value="Poison Lizard Pokemon">Poison Lizard Pokemon</option>
					<option value="Poison Moth Pokemon">Poison Moth Pokemon</option>
					<option value="Poison Pin Pokemon">Poison Pin Pokemon</option>
					<option value="Poison Stab Pokemon">Poison Stab Pokemon</option>
					<option value="Polka Dot Pokemon">Polka Dot Pokemon</option>
					<option value="Poodle Pokemon">Poodle Pokemon</option>
					<option value="Powder Blowing Pokemon">Powder Blowing Pokemon</option>
					<option value="Pride Pokemon">Pride Pokemon</option>
					<option value="Prim and Proper Pokemon">Prim and Proper Pokemon</option>
					<option value="Prism Pokemon">Prism Pokemon</option>
					<option value="Protostar Pokemon">Protostar Pokemon</option>
					<option value="Prowling Pokemon">Prowling Pokemon</option>
					<option value="Pseudo Grass Pokemon">Pseudo Grass Pokemon</option>
					<option value="Pseudo-Bird Pokemon">Pseudo-Bird Pokemon</option>
					<option value="Psychic Power Pokemon">Psychic Power Pokemon</option>
					<option value="Pumpkin Pokemon">Pumpkin Pokemon</option>
					<option value="Punch Pokemon">Punch Pokemon</option>
					<option value="Punk Pokemon">Punk Pokemon</option>
					<option value="Puppy Pokemon">Puppy Pokemon</option>
					<option value="Quiet Pokemon">Quiet Pokemon</option>
					<option value="Rabbit Pokemon">Rabbit Pokemon</option>
					<option value="Radome Pokemon">Radome Pokemon</option>
					<option value="Raging Fire Pokemon">Raging Fire Pokemon</option>
					<option value="Raging Flames Pokemon">Raging Flames Pokemon</option>
					<option value="Rainbow-Colored Pokemon">Rainbow-Colored Pokemon</option>
					<option value="Rampage Horse Pokemon">Rampage Horse Pokemon</option>
					<option value="Rampaging Monkey Pokemon">Rampaging Monkey Pokemon</option>
					<option value="Raven Pokemon">Raven Pokemon</option>
					<option value="Rebellious Pokemon">Rebellious Pokemon</option>
					<option value="Rendezvous Pokemon">Rendezvous Pokemon</option>
					<option value="Reproachful Pokemon">Reproachful Pokemon</option>
					<option value="Restraint Pokemon">Restraint Pokemon</option>
					<option value="Reversal Pokemon">Reversal Pokemon</option>
					<option value="Ride Pokemon">Ride Pokemon</option>
					<option value="Ripple Pokemon">Ripple Pokemon</option>
					<option value="Rock Hermit Pokemon">Rock Hermit Pokemon</option>
					<option value="Rock Pokemon">Rock Pokemon</option>
					<option value="Rock Skin Pokemon">Rock Skin Pokemon</option>
					<option value="Rock Snake Pokemon">Rock Snake Pokemon</option>
					<option value="Rocky Mountain Pokemon">Rocky Mountain Pokemon</option>
					<option value="Rogue Pokemon">Rogue Pokemon</option>
					<option value="Root Pokemon">Root Pokemon</option>
					<option value="Rotation Pokemon">Rotation Pokemon</option>
					<option value="Round Mouse Pokemon">Round Mouse Pokemon</option>
					<option value="Royal Pokemon">Royal Pokemon</option>
					<option value="Royal Sword Pokemon">Royal Sword Pokemon</option>
					<option value="Ruffian Pokemon">Ruffian Pokemon</option>
					<option value="Rush Pokemon">Rush Pokemon</option>
					<option value="Rushing Pokemon">Rushing Pokemon</option>
					<option value="Sage Pokemon">Sage Pokemon</option>
					<option value="Sand Castle Pokemon">Sand Castle Pokemon</option>
					<option value="Sand Pile Pokemon">Sand Pile Pokemon</option>
					<option value="Sand Snake Pokemon">Sand Snake Pokemon</option>
					<option value="Scale Pokemon">Scale Pokemon</option>
					<option value="Scarecrow Plant Pokemon">Scarecrow Plant Pokemon</option>
					<option value="Scarf Pokemon">Scarf Pokemon</option>
					<option value="Scorpion Pokemon">Scorpion Pokemon</option>
					<option value="Scoundrel Pokemon">Scoundrel Pokemon</option>
					<option value="Scuffle Pokemon">Scuffle Pokemon</option>
					<option value="Sea Cucumber Pokemon">Sea Cucumber Pokemon</option>
					<option value="Sea Lily Pokemon">Sea Lily Pokemon</option>
					<option value="Sea Lion Pokemon">Sea Lion Pokemon</option>
					<option value="Sea Otter Pokemon">Sea Otter Pokemon</option>
					<option value="Sea Slug Pokemon">Sea Slug Pokemon</option>
					<option value="Sea Urchin Pokemon">Sea Urchin Pokemon</option>
					<option value="Sea Weasel Pokemon">Sea Weasel Pokemon</option>
					<option value="Seabed Pokemon">Seabed Pokemon</option>
					<option value="Sealed Pokemon">Sealed Pokemon</option>
					<option value="Seasonal Pokemon">Seasonal Pokemon</option>
					<option value="Seaweed Pokemon">Seaweed Pokemon</option>
					<option value="Seed Pokemon">Seed Pokemon</option>
					<option value="Self-control Pokemon">Self-control Pokemon</option>
					<option value="Seven Spot Pokemon">Seven Spot Pokemon</option>
					<option value="Sewing Pokemon">Sewing Pokemon</option>
					<option value="Shadow Dweller Pokemon">Shadow Dweller Pokemon</option>
					<option value="Shadow Pokemon">Shadow Pokemon</option>
					<option value="Shaman Pokemon">Shaman Pokemon</option>
					<option value="Sharp Edge Pokemon">Sharp Edge Pokemon</option>
					<option value="Shedding Pokemon">Shedding Pokemon</option>
					<option value="Sheep Pokemon">Sheep Pokemon</option>
					<option value="Shell Pokemon">Shell Pokemon</option>
					<option value="Shelled Chestnut Pokemon">Shelled Chestnut Pokemon</option>
					<option value="Shelled Pokemon">Shelled Pokemon</option>
					<option value="Shield Pokemon">Shield Pokemon</option>
					<option value="Siamese Cat Pokemon">Siamese Cat Pokemon</option>
					<option value="Sickle Grass Pokemon">Sickle Grass Pokemon</option>
					<option value="Silent Pokemon">Silent Pokemon</option>
					<option value="Single Flower Pokemon">Single Flower Pokemon</option>
					<option value="Single Horn Pokemon">Single Horn Pokemon</option>
					<option value="Skewer Pokemon">Skewer Pokemon</option>
					<option value="Skunk Pokemon">Skunk Pokemon</option>
					<option value="Sky Pokemon">Sky Pokemon</option>
					<option value="Sloth Pokemon">Sloth Pokemon</option>
					<option value="Sludge Pokemon">Sludge Pokemon</option>
					<option value="Small Bear Pokemon">Small Bear Pokemon</option>
					<option value="Small Fish Pokemon">Small Fish Pokemon</option>
					<option value="Small Monkey Pokemon">Small Monkey Pokemon</option>
					<option value="Small Mouse Pokemon">Small Mouse Pokemon</option>
					<option value="Small Pigeon Pokemon">Small Pigeon Pokemon</option>
					<option value="Small Swallow Pokemon">Small Swallow Pokemon</option>
					<option value="Snail Pokemon">Snail Pokemon</option>
					<option value="Snake Pokemon">Snake Pokemon</option>
					<option value="Snapping Pokemon">Snapping Pokemon</option>
					<option value="Snow Country Pokemon">Snow Country Pokemon</option>
					<option value="Snow Umbrella Pokemon">Snow Umbrella Pokemon</option>
					<option value="Soft Body Pokemon">Soft Body Pokemon</option>
					<option value="Soloist Pokemon">Soloist Pokemon</option>
					<option value="Sound Wave Pokemon">Sound Wave Pokemon</option>
					<option value="South Sea Pokemon">South Sea Pokemon</option>
					<option value="Space Pokemon">Space Pokemon</option>
					<option value="Sparks Pokemon">Sparks Pokemon</option>
					<option value="Sphere Pokemon">Sphere Pokemon</option>
					<option value="Spike Ball Pokemon">Spike Ball Pokemon</option>
					<option value="Spike Seed Pokemon">Spike Seed Pokemon</option>
					<option value="Spiky Armor Pokemon">Spiky Armor Pokemon</option>
					<option value="Spiky Pokemon">Spiky Pokemon</option>
					<option value="Spin Pokemon">Spin Pokemon</option>
					<option value="Spiral Pokemon">Spiral Pokemon</option>
					<option value="Spirit Pokemon">Spirit Pokemon</option>
					<option value="Spitfire Pokemon">Spitfire Pokemon</option>
					<option value="Spoiled Pokemon">Spoiled Pokemon</option>
					<option value="Spot Panda Pokemon">Spot Panda Pokemon</option>
					<option value="Spot-Billed Duck Pokemon">Spot-Billed Duck Pokemon</option>
					<option value="Stag Beetle Pokemon">Stag Beetle Pokemon</option>
					<option value="Stakeout Pokemon">Stakeout Pokemon</option>
					<option value="Star Shape Pokemon">Star Shape Pokemon</option>
					<option value="Stare Pokemon">Stare Pokemon</option>
					<option value="Starling Pokemon">Starling Pokemon</option>
					<option value="Stealth Pokemon">Stealth Pokemon</option>
					<option value="Steam Pokemon">Steam Pokemon</option>
					<option value="Stomach Pokemon">Stomach Pokemon</option>
					<option value="Stone Cup Pokemon">Stone Cup Pokemon</option>
					<option value="Stone Hermit Pokemon">Stone Hermit Pokemon</option>
					<option value="Stone Wall Pokemon">Stone Wall Pokemon</option>
					<option value="Striker Pokemon">Striker Pokemon</option>
					<option value="String-Spitting Pokemon">String-Spitting Pokemon</option>
					<option value="Strong Arm Pokemon">Strong Arm Pokemon</option>
					<option value="Stuffed Cheeks Pokemon">Stuffed Cheeks Pokemon</option>
					<option value="Stuffed Toy Pokemon">Stuffed Toy Pokemon</option>
					<option value="Stump Pokemon">Stump Pokemon</option>
					<option value="Stupid Pokemon">Stupid Pokemon</option>
					<option value="Sun Pokemon">Sun Pokemon</option>
					<option value="Superhuman Strength Pokemon">Superhuman Strength Pokemon</option>
					<option value="Swallow Pokemon">Swallow Pokemon</option>
					<option value="Swamp Fish Pokemon">Swamp Fish Pokemon</option>
					<option value="Swan Pokemon">Swan Pokemon</option>
					<option value="Swift Horse Pokemon">Swift Horse Pokemon</option>
					<option value="Swollen Pokemon">Swollen Pokemon</option>
					<option value="Sword Blade Pokemon">Sword Blade Pokemon</option>
					<option value="Sword Pokemon">Sword Pokemon</option>
					<option value="Symbol Pokemon">Symbol Pokemon</option>
					<option value="Tadpole Pokemon">Tadpole Pokemon</option>
					<option value="Temptation Pokemon">Temptation Pokemon</option>
					<option value="Thickheaded Pokemon">Thickheaded Pokemon</option>
					<option value="Thin Wing Pokemon">Thin Wing Pokemon</option>
					<option value="Thorn Monkey Pokemon">Thorn Monkey Pokemon</option>
					<option value="Thorn Pokemon">Thorn Pokemon</option>
					<option value="Thunder and Lightning Pokemon">Thunder and Lightning Pokemon</option>
					<option value="Thunder Pokemon">Thunder Pokemon</option>
					<option value="Thunderclap Pokemon">Thunderclap Pokemon</option>
					<option value="Tiger Cat Pokemon">Tiger Cat Pokemon</option>
					<option value="Time Pokemon">Time Pokemon</option>
					<option value="Time Traveling Pokemon">Time Traveling Pokemon</option>
					<option value="Tiny Bird Pokemon">Tiny Bird Pokemon</option>
					<option value="Tiny Raccoon Dog Pokemon">Tiny Raccoon Dog Pokemon</option>
					<option value="Tolerant Pokemon">Tolerant Pokemon</option>
					<option value="Torch Pokemon">Torch Pokemon</option>
					<option value="Training Pokemon">Training Pokemon</option>
					<option value="Trance Pokemon">Trance Pokemon</option>
					<option value="Transformation Pokemon">Transformation Pokemon</option>
					<option value="Transport Pokemon">Transport Pokemon</option>
					<option value="Trap Pokemon">Trap Pokemon</option>
					<option value="Triplet Bird Pokemon">Triplet Bird Pokemon</option>
					<option value="Tundra Pokemon">Tundra Pokemon</option>
					<option value="Turtle Pokemon">Turtle Pokemon</option>
					<option value="Tusk Pokemon">Tusk Pokemon</option>
					<option value="Twin Bird Pokemon">Twin Bird Pokemon</option>
					<option value="Twin Tusk Pokemon">Twin Tusk Pokemon</option>
					<option value="Two Groups Pokemon">Two Groups Pokemon</option>
					<option value="Two-Faced Pokemon">Two-Faced Pokemon</option>
					<option value="Tyrant Pokemon">Tyrant Pokemon</option>
					<option value="Vibration Pokemon">Vibration Pokemon</option>
					<option value="Victory Pokemon">Victory Pokemon</option>
					<option value="Vigilant Pokemon">Vigilant Pokemon</option>
					<option value="Viking Pokemon">Viking Pokemon</option>
					<option value="Vine Pokemon">Vine Pokemon</option>
					<option value="Violent Pokemon">Violent Pokemon</option>
					<option value="Virtual Pokemon">Virtual Pokemon</option>
					<option value="Volcano Pokemon">Volcano Pokemon</option>
					<option value="War Cry Pokemon">War Cry Pokemon</option>
					<option value="Warrior Pokemon">Warrior Pokemon</option>
					<option value="Water Bubble Pokemon">Water Bubble Pokemon</option>
					<option value="Water Fish Pokemon">Water Fish Pokemon</option>
					<option value="Water Gun Pokemon">Water Gun Pokemon</option>
					<option value="Water Lizard Pokemon">Water Lizard Pokemon</option>
					<option value="Water Mouse Pokemon">Water Mouse Pokemon</option>
					<option value="Water Rabbit Pokemon">Water Rabbit Pokemon</option>
					<option value="Water Splash Pokemon">Water Splash Pokemon</option>
					<option value="Water Strider Pokemon">Water Strider Pokemon</option>
					<option value="Waterfowl Pokemon">Waterfowl Pokemon</option>
					<option value="Wave Pokemon">Wave Pokemon</option>
					<option value="Weather Pokemon">Weather Pokemon</option>
					<option value="Weed Pokemon">Weed Pokemon</option>
					<option value="Whipped Cream Pokemon">Whipped Cream Pokemon</option>
					<option value="Whirlwind Pokemon">Whirlwind Pokemon</option>
					<option value="Whisker Fish Pokemon">Whisker Fish Pokemon</option>
					<option value="Whisper Pokemon">Whisper Pokemon</option>
					<option value="White Yang Pokemon">White Yang Pokemon</option>
					<option value="Wicked Pokemon">Wicked Pokemon</option>
					<option value="Wild Boar Pokemon">Wild Boar Pokemon</option>
					<option value="Wild Bull Pokemon">Wild Bull Pokemon</option>
					<option value="Wild Pigeon Pokemon">Wild Pigeon Pokemon</option>
					<option value="Wild Pokemon">Wild Pokemon</option>
					<option value="Will Pokemon">Will Pokemon</option>
					<option value="Wind Chime Pokemon">Wind Chime Pokemon</option>
					<option value="Wind-Hidden Pokemon">Wind-Hidden Pokemon</option>
					<option value="Wing Fish Pokemon">Wing Fish Pokemon</option>
					<option value="Wish Pokemon">Wish Pokemon</option>
					<option value="Wolf Pokemon">Wolf Pokemon</option>
					<option value="Woodpecker Pokemon">Woodpecker Pokemon</option>
					<option value="Wrestling Pokemon">Wrestling Pokemon</option>
					<option value="Young Colt Pokemon">Young Colt Pokemon</option>
					<option value="Young Lion Pokemon">Young Lion Pokemon</option>
					<option value="Young Lord Pokemon">Young Lord Pokemon</option>
					<option value="Young Turtle Pokemon">Young Turtle Pokemon</option>
				</select><br>
				<label for="dex1" class="formLabels">Description:</label>
				<textarea name="dex1" id="dex1" rows="4" cols="50">Describe your pokemon, its nature, or its history and lore here.</textarea><br>
				<label for="url" class="formLabels">Add an optional URL for an image of your pokemon:</label>
				<input type="text" name="url" id="url"><br>
				<input type="submit" value="Create Pokemon"/>
			</form>
		</section>

	</main>
	<jsp:include page='bootstrapFoot.jsp'></jsp:include>
</body>
</html>